//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubeforce Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	url "net/url"
	unsafe "unsafe"

	agent "k3f.io/kubeforce/agent/pkg/apis/agent"
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Condition)(nil), (*agent.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Condition_To_agent_Condition(a.(*Condition), b.(*agent.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*agent.Condition)(nil), (*Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_agent_Condition_To_v1alpha1_Condition(a.(*agent.Condition), b.(*Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Interface)(nil), (*agent.Interface)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Interface_To_agent_Interface(a.(*Interface), b.(*agent.Interface), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*agent.Interface)(nil), (*Interface)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_agent_Interface_To_v1alpha1_Interface(a.(*agent.Interface), b.(*Interface), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Network)(nil), (*agent.Network)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Network_To_agent_Network(a.(*Network), b.(*agent.Network), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*agent.Network)(nil), (*Network)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_agent_Network_To_v1alpha1_Network(a.(*agent.Network), b.(*Network), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Playbook)(nil), (*agent.Playbook)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Playbook_To_agent_Playbook(a.(*Playbook), b.(*agent.Playbook), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*agent.Playbook)(nil), (*Playbook)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_agent_Playbook_To_v1alpha1_Playbook(a.(*agent.Playbook), b.(*Playbook), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PlaybookDeployment)(nil), (*agent.PlaybookDeployment)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PlaybookDeployment_To_agent_PlaybookDeployment(a.(*PlaybookDeployment), b.(*agent.PlaybookDeployment), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*agent.PlaybookDeployment)(nil), (*PlaybookDeployment)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_agent_PlaybookDeployment_To_v1alpha1_PlaybookDeployment(a.(*agent.PlaybookDeployment), b.(*PlaybookDeployment), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PlaybookDeploymentList)(nil), (*agent.PlaybookDeploymentList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PlaybookDeploymentList_To_agent_PlaybookDeploymentList(a.(*PlaybookDeploymentList), b.(*agent.PlaybookDeploymentList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*agent.PlaybookDeploymentList)(nil), (*PlaybookDeploymentList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_agent_PlaybookDeploymentList_To_v1alpha1_PlaybookDeploymentList(a.(*agent.PlaybookDeploymentList), b.(*PlaybookDeploymentList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PlaybookDeploymentSpec)(nil), (*agent.PlaybookDeploymentSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PlaybookDeploymentSpec_To_agent_PlaybookDeploymentSpec(a.(*PlaybookDeploymentSpec), b.(*agent.PlaybookDeploymentSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*agent.PlaybookDeploymentSpec)(nil), (*PlaybookDeploymentSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_agent_PlaybookDeploymentSpec_To_v1alpha1_PlaybookDeploymentSpec(a.(*agent.PlaybookDeploymentSpec), b.(*PlaybookDeploymentSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PlaybookDeploymentStatus)(nil), (*agent.PlaybookDeploymentStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PlaybookDeploymentStatus_To_agent_PlaybookDeploymentStatus(a.(*PlaybookDeploymentStatus), b.(*agent.PlaybookDeploymentStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*agent.PlaybookDeploymentStatus)(nil), (*PlaybookDeploymentStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_agent_PlaybookDeploymentStatus_To_v1alpha1_PlaybookDeploymentStatus(a.(*agent.PlaybookDeploymentStatus), b.(*PlaybookDeploymentStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PlaybookList)(nil), (*agent.PlaybookList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PlaybookList_To_agent_PlaybookList(a.(*PlaybookList), b.(*agent.PlaybookList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*agent.PlaybookList)(nil), (*PlaybookList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_agent_PlaybookList_To_v1alpha1_PlaybookList(a.(*agent.PlaybookList), b.(*PlaybookList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PlaybookLogOptions)(nil), (*agent.PlaybookLogOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PlaybookLogOptions_To_agent_PlaybookLogOptions(a.(*PlaybookLogOptions), b.(*agent.PlaybookLogOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*agent.PlaybookLogOptions)(nil), (*PlaybookLogOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_agent_PlaybookLogOptions_To_v1alpha1_PlaybookLogOptions(a.(*agent.PlaybookLogOptions), b.(*PlaybookLogOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PlaybookSpec)(nil), (*agent.PlaybookSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PlaybookSpec_To_agent_PlaybookSpec(a.(*PlaybookSpec), b.(*agent.PlaybookSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*agent.PlaybookSpec)(nil), (*PlaybookSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_agent_PlaybookSpec_To_v1alpha1_PlaybookSpec(a.(*agent.PlaybookSpec), b.(*PlaybookSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PlaybookStatus)(nil), (*agent.PlaybookStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PlaybookStatus_To_agent_PlaybookStatus(a.(*PlaybookStatus), b.(*agent.PlaybookStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*agent.PlaybookStatus)(nil), (*PlaybookStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_agent_PlaybookStatus_To_v1alpha1_PlaybookStatus(a.(*agent.PlaybookStatus), b.(*PlaybookStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PlaybookTemplateSpec)(nil), (*agent.PlaybookTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PlaybookTemplateSpec_To_agent_PlaybookTemplateSpec(a.(*PlaybookTemplateSpec), b.(*agent.PlaybookTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*agent.PlaybookTemplateSpec)(nil), (*PlaybookTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_agent_PlaybookTemplateSpec_To_v1alpha1_PlaybookTemplateSpec(a.(*agent.PlaybookTemplateSpec), b.(*PlaybookTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Policy)(nil), (*agent.Policy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Policy_To_agent_Policy(a.(*Policy), b.(*agent.Policy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*agent.Policy)(nil), (*Policy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_agent_Policy_To_v1alpha1_Policy(a.(*agent.Policy), b.(*Policy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SysInfo)(nil), (*agent.SysInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SysInfo_To_agent_SysInfo(a.(*SysInfo), b.(*agent.SysInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*agent.SysInfo)(nil), (*SysInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_agent_SysInfo_To_v1alpha1_SysInfo(a.(*agent.SysInfo), b.(*SysInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SysInfoSpec)(nil), (*agent.SysInfoSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SysInfoSpec_To_agent_SysInfoSpec(a.(*SysInfoSpec), b.(*agent.SysInfoSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*agent.SysInfoSpec)(nil), (*SysInfoSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_agent_SysInfoSpec_To_v1alpha1_SysInfoSpec(a.(*agent.SysInfoSpec), b.(*SysInfoSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*url.Values)(nil), (*PlaybookLogOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_url_Values_To_v1alpha1_PlaybookLogOptions(a.(*url.Values), b.(*PlaybookLogOptions), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Condition_To_agent_Condition(in *Condition, out *agent.Condition, s conversion.Scope) error {
	out.Type = agent.ConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1alpha1_Condition_To_agent_Condition is an autogenerated conversion function.
func Convert_v1alpha1_Condition_To_agent_Condition(in *Condition, out *agent.Condition, s conversion.Scope) error {
	return autoConvert_v1alpha1_Condition_To_agent_Condition(in, out, s)
}

func autoConvert_agent_Condition_To_v1alpha1_Condition(in *agent.Condition, out *Condition, s conversion.Scope) error {
	out.Type = ConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_agent_Condition_To_v1alpha1_Condition is an autogenerated conversion function.
func Convert_agent_Condition_To_v1alpha1_Condition(in *agent.Condition, out *Condition, s conversion.Scope) error {
	return autoConvert_agent_Condition_To_v1alpha1_Condition(in, out, s)
}

func autoConvert_v1alpha1_Interface_To_agent_Interface(in *Interface, out *agent.Interface, s conversion.Scope) error {
	out.Name = in.Name
	out.Address = in.Address
	out.Mac = in.Mac
	out.Status = agent.InterfaceStatus(in.Status)
	return nil
}

// Convert_v1alpha1_Interface_To_agent_Interface is an autogenerated conversion function.
func Convert_v1alpha1_Interface_To_agent_Interface(in *Interface, out *agent.Interface, s conversion.Scope) error {
	return autoConvert_v1alpha1_Interface_To_agent_Interface(in, out, s)
}

func autoConvert_agent_Interface_To_v1alpha1_Interface(in *agent.Interface, out *Interface, s conversion.Scope) error {
	out.Name = in.Name
	out.Address = in.Address
	out.Mac = in.Mac
	out.Status = InterfaceStatus(in.Status)
	return nil
}

// Convert_agent_Interface_To_v1alpha1_Interface is an autogenerated conversion function.
func Convert_agent_Interface_To_v1alpha1_Interface(in *agent.Interface, out *Interface, s conversion.Scope) error {
	return autoConvert_agent_Interface_To_v1alpha1_Interface(in, out, s)
}

func autoConvert_v1alpha1_Network_To_agent_Network(in *Network, out *agent.Network, s conversion.Scope) error {
	out.Hostname = in.Hostname
	out.InternalIP = in.InternalIP
	out.Interfaces = *(*[]agent.Interface)(unsafe.Pointer(&in.Interfaces))
	return nil
}

// Convert_v1alpha1_Network_To_agent_Network is an autogenerated conversion function.
func Convert_v1alpha1_Network_To_agent_Network(in *Network, out *agent.Network, s conversion.Scope) error {
	return autoConvert_v1alpha1_Network_To_agent_Network(in, out, s)
}

func autoConvert_agent_Network_To_v1alpha1_Network(in *agent.Network, out *Network, s conversion.Scope) error {
	out.Hostname = in.Hostname
	out.InternalIP = in.InternalIP
	out.Interfaces = *(*[]Interface)(unsafe.Pointer(&in.Interfaces))
	return nil
}

// Convert_agent_Network_To_v1alpha1_Network is an autogenerated conversion function.
func Convert_agent_Network_To_v1alpha1_Network(in *agent.Network, out *Network, s conversion.Scope) error {
	return autoConvert_agent_Network_To_v1alpha1_Network(in, out, s)
}

func autoConvert_v1alpha1_Playbook_To_agent_Playbook(in *Playbook, out *agent.Playbook, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_PlaybookSpec_To_agent_PlaybookSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_PlaybookStatus_To_agent_PlaybookStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Playbook_To_agent_Playbook is an autogenerated conversion function.
func Convert_v1alpha1_Playbook_To_agent_Playbook(in *Playbook, out *agent.Playbook, s conversion.Scope) error {
	return autoConvert_v1alpha1_Playbook_To_agent_Playbook(in, out, s)
}

func autoConvert_agent_Playbook_To_v1alpha1_Playbook(in *agent.Playbook, out *Playbook, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_agent_PlaybookSpec_To_v1alpha1_PlaybookSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_agent_PlaybookStatus_To_v1alpha1_PlaybookStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_agent_Playbook_To_v1alpha1_Playbook is an autogenerated conversion function.
func Convert_agent_Playbook_To_v1alpha1_Playbook(in *agent.Playbook, out *Playbook, s conversion.Scope) error {
	return autoConvert_agent_Playbook_To_v1alpha1_Playbook(in, out, s)
}

func autoConvert_v1alpha1_PlaybookDeployment_To_agent_PlaybookDeployment(in *PlaybookDeployment, out *agent.PlaybookDeployment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_PlaybookDeploymentSpec_To_agent_PlaybookDeploymentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_PlaybookDeploymentStatus_To_agent_PlaybookDeploymentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_PlaybookDeployment_To_agent_PlaybookDeployment is an autogenerated conversion function.
func Convert_v1alpha1_PlaybookDeployment_To_agent_PlaybookDeployment(in *PlaybookDeployment, out *agent.PlaybookDeployment, s conversion.Scope) error {
	return autoConvert_v1alpha1_PlaybookDeployment_To_agent_PlaybookDeployment(in, out, s)
}

func autoConvert_agent_PlaybookDeployment_To_v1alpha1_PlaybookDeployment(in *agent.PlaybookDeployment, out *PlaybookDeployment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_agent_PlaybookDeploymentSpec_To_v1alpha1_PlaybookDeploymentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_agent_PlaybookDeploymentStatus_To_v1alpha1_PlaybookDeploymentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_agent_PlaybookDeployment_To_v1alpha1_PlaybookDeployment is an autogenerated conversion function.
func Convert_agent_PlaybookDeployment_To_v1alpha1_PlaybookDeployment(in *agent.PlaybookDeployment, out *PlaybookDeployment, s conversion.Scope) error {
	return autoConvert_agent_PlaybookDeployment_To_v1alpha1_PlaybookDeployment(in, out, s)
}

func autoConvert_v1alpha1_PlaybookDeploymentList_To_agent_PlaybookDeploymentList(in *PlaybookDeploymentList, out *agent.PlaybookDeploymentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]agent.PlaybookDeployment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_PlaybookDeploymentList_To_agent_PlaybookDeploymentList is an autogenerated conversion function.
func Convert_v1alpha1_PlaybookDeploymentList_To_agent_PlaybookDeploymentList(in *PlaybookDeploymentList, out *agent.PlaybookDeploymentList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PlaybookDeploymentList_To_agent_PlaybookDeploymentList(in, out, s)
}

func autoConvert_agent_PlaybookDeploymentList_To_v1alpha1_PlaybookDeploymentList(in *agent.PlaybookDeploymentList, out *PlaybookDeploymentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]PlaybookDeployment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_agent_PlaybookDeploymentList_To_v1alpha1_PlaybookDeploymentList is an autogenerated conversion function.
func Convert_agent_PlaybookDeploymentList_To_v1alpha1_PlaybookDeploymentList(in *agent.PlaybookDeploymentList, out *PlaybookDeploymentList, s conversion.Scope) error {
	return autoConvert_agent_PlaybookDeploymentList_To_v1alpha1_PlaybookDeploymentList(in, out, s)
}

func autoConvert_v1alpha1_PlaybookDeploymentSpec_To_agent_PlaybookDeploymentSpec(in *PlaybookDeploymentSpec, out *agent.PlaybookDeploymentSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_PlaybookTemplateSpec_To_agent_PlaybookTemplateSpec(&in.Template, &out.Template, s); err != nil {
		return err
	}
	out.RevisionHistoryLimit = (*int32)(unsafe.Pointer(in.RevisionHistoryLimit))
	out.Paused = in.Paused
	return nil
}

// Convert_v1alpha1_PlaybookDeploymentSpec_To_agent_PlaybookDeploymentSpec is an autogenerated conversion function.
func Convert_v1alpha1_PlaybookDeploymentSpec_To_agent_PlaybookDeploymentSpec(in *PlaybookDeploymentSpec, out *agent.PlaybookDeploymentSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PlaybookDeploymentSpec_To_agent_PlaybookDeploymentSpec(in, out, s)
}

func autoConvert_agent_PlaybookDeploymentSpec_To_v1alpha1_PlaybookDeploymentSpec(in *agent.PlaybookDeploymentSpec, out *PlaybookDeploymentSpec, s conversion.Scope) error {
	if err := Convert_agent_PlaybookTemplateSpec_To_v1alpha1_PlaybookTemplateSpec(&in.Template, &out.Template, s); err != nil {
		return err
	}
	out.RevisionHistoryLimit = (*int32)(unsafe.Pointer(in.RevisionHistoryLimit))
	out.Paused = in.Paused
	return nil
}

// Convert_agent_PlaybookDeploymentSpec_To_v1alpha1_PlaybookDeploymentSpec is an autogenerated conversion function.
func Convert_agent_PlaybookDeploymentSpec_To_v1alpha1_PlaybookDeploymentSpec(in *agent.PlaybookDeploymentSpec, out *PlaybookDeploymentSpec, s conversion.Scope) error {
	return autoConvert_agent_PlaybookDeploymentSpec_To_v1alpha1_PlaybookDeploymentSpec(in, out, s)
}

func autoConvert_v1alpha1_PlaybookDeploymentStatus_To_agent_PlaybookDeploymentStatus(in *PlaybookDeploymentStatus, out *agent.PlaybookDeploymentStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.Phase = agent.PlaybookDeploymentPhase(in.Phase)
	return nil
}

// Convert_v1alpha1_PlaybookDeploymentStatus_To_agent_PlaybookDeploymentStatus is an autogenerated conversion function.
func Convert_v1alpha1_PlaybookDeploymentStatus_To_agent_PlaybookDeploymentStatus(in *PlaybookDeploymentStatus, out *agent.PlaybookDeploymentStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_PlaybookDeploymentStatus_To_agent_PlaybookDeploymentStatus(in, out, s)
}

func autoConvert_agent_PlaybookDeploymentStatus_To_v1alpha1_PlaybookDeploymentStatus(in *agent.PlaybookDeploymentStatus, out *PlaybookDeploymentStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.Phase = PlaybookDeploymentPhase(in.Phase)
	return nil
}

// Convert_agent_PlaybookDeploymentStatus_To_v1alpha1_PlaybookDeploymentStatus is an autogenerated conversion function.
func Convert_agent_PlaybookDeploymentStatus_To_v1alpha1_PlaybookDeploymentStatus(in *agent.PlaybookDeploymentStatus, out *PlaybookDeploymentStatus, s conversion.Scope) error {
	return autoConvert_agent_PlaybookDeploymentStatus_To_v1alpha1_PlaybookDeploymentStatus(in, out, s)
}

func autoConvert_v1alpha1_PlaybookList_To_agent_PlaybookList(in *PlaybookList, out *agent.PlaybookList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]agent.Playbook)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_PlaybookList_To_agent_PlaybookList is an autogenerated conversion function.
func Convert_v1alpha1_PlaybookList_To_agent_PlaybookList(in *PlaybookList, out *agent.PlaybookList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PlaybookList_To_agent_PlaybookList(in, out, s)
}

func autoConvert_agent_PlaybookList_To_v1alpha1_PlaybookList(in *agent.PlaybookList, out *PlaybookList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Playbook)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_agent_PlaybookList_To_v1alpha1_PlaybookList is an autogenerated conversion function.
func Convert_agent_PlaybookList_To_v1alpha1_PlaybookList(in *agent.PlaybookList, out *PlaybookList, s conversion.Scope) error {
	return autoConvert_agent_PlaybookList_To_v1alpha1_PlaybookList(in, out, s)
}

func autoConvert_v1alpha1_PlaybookLogOptions_To_agent_PlaybookLogOptions(in *PlaybookLogOptions, out *agent.PlaybookLogOptions, s conversion.Scope) error {
	out.Follow = in.Follow
	out.Previous = in.Previous
	out.SinceSeconds = (*int64)(unsafe.Pointer(in.SinceSeconds))
	out.SinceTime = (*metav1.Time)(unsafe.Pointer(in.SinceTime))
	out.Timestamps = in.Timestamps
	out.TailLines = (*int64)(unsafe.Pointer(in.TailLines))
	return nil
}

// Convert_v1alpha1_PlaybookLogOptions_To_agent_PlaybookLogOptions is an autogenerated conversion function.
func Convert_v1alpha1_PlaybookLogOptions_To_agent_PlaybookLogOptions(in *PlaybookLogOptions, out *agent.PlaybookLogOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_PlaybookLogOptions_To_agent_PlaybookLogOptions(in, out, s)
}

func autoConvert_agent_PlaybookLogOptions_To_v1alpha1_PlaybookLogOptions(in *agent.PlaybookLogOptions, out *PlaybookLogOptions, s conversion.Scope) error {
	out.Follow = in.Follow
	out.Previous = in.Previous
	out.SinceSeconds = (*int64)(unsafe.Pointer(in.SinceSeconds))
	out.SinceTime = (*metav1.Time)(unsafe.Pointer(in.SinceTime))
	out.Timestamps = in.Timestamps
	out.TailLines = (*int64)(unsafe.Pointer(in.TailLines))
	return nil
}

// Convert_agent_PlaybookLogOptions_To_v1alpha1_PlaybookLogOptions is an autogenerated conversion function.
func Convert_agent_PlaybookLogOptions_To_v1alpha1_PlaybookLogOptions(in *agent.PlaybookLogOptions, out *PlaybookLogOptions, s conversion.Scope) error {
	return autoConvert_agent_PlaybookLogOptions_To_v1alpha1_PlaybookLogOptions(in, out, s)
}

func autoConvert_url_Values_To_v1alpha1_PlaybookLogOptions(in *url.Values, out *PlaybookLogOptions, s conversion.Scope) error {
	// WARNING: Field TypeMeta does not have json tag, skipping.

	if values, ok := map[string][]string(*in)["follow"]; ok && len(values) > 0 {
		if err := runtime.Convert_Slice_string_To_bool(&values, &out.Follow, s); err != nil {
			return err
		}
	} else {
		out.Follow = false
	}
	if values, ok := map[string][]string(*in)["previous"]; ok && len(values) > 0 {
		if err := runtime.Convert_Slice_string_To_bool(&values, &out.Previous, s); err != nil {
			return err
		}
	} else {
		out.Previous = false
	}
	if values, ok := map[string][]string(*in)["sinceSeconds"]; ok && len(values) > 0 {
		if err := runtime.Convert_Slice_string_To_Pointer_int64(&values, &out.SinceSeconds, s); err != nil {
			return err
		}
	} else {
		out.SinceSeconds = nil
	}
	if values, ok := map[string][]string(*in)["sinceTime"]; ok && len(values) > 0 {
		if err := metav1.Convert_Slice_string_To_Pointer_v1_Time(&values, &out.SinceTime, s); err != nil {
			return err
		}
	} else {
		out.SinceTime = nil
	}
	if values, ok := map[string][]string(*in)["timestamps"]; ok && len(values) > 0 {
		if err := runtime.Convert_Slice_string_To_bool(&values, &out.Timestamps, s); err != nil {
			return err
		}
	} else {
		out.Timestamps = false
	}
	if values, ok := map[string][]string(*in)["tailLines"]; ok && len(values) > 0 {
		if err := runtime.Convert_Slice_string_To_Pointer_int64(&values, &out.TailLines, s); err != nil {
			return err
		}
	} else {
		out.TailLines = nil
	}
	return nil
}

// Convert_url_Values_To_v1alpha1_PlaybookLogOptions is an autogenerated conversion function.
func Convert_url_Values_To_v1alpha1_PlaybookLogOptions(in *url.Values, out *PlaybookLogOptions, s conversion.Scope) error {
	return autoConvert_url_Values_To_v1alpha1_PlaybookLogOptions(in, out, s)
}

func autoConvert_v1alpha1_PlaybookSpec_To_agent_PlaybookSpec(in *PlaybookSpec, out *agent.PlaybookSpec, s conversion.Scope) error {
	out.Policy = (*agent.Policy)(unsafe.Pointer(in.Policy))
	out.Files = *(*map[string]string)(unsafe.Pointer(&in.Files))
	out.Entrypoint = in.Entrypoint
	return nil
}

// Convert_v1alpha1_PlaybookSpec_To_agent_PlaybookSpec is an autogenerated conversion function.
func Convert_v1alpha1_PlaybookSpec_To_agent_PlaybookSpec(in *PlaybookSpec, out *agent.PlaybookSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PlaybookSpec_To_agent_PlaybookSpec(in, out, s)
}

func autoConvert_agent_PlaybookSpec_To_v1alpha1_PlaybookSpec(in *agent.PlaybookSpec, out *PlaybookSpec, s conversion.Scope) error {
	out.Policy = (*Policy)(unsafe.Pointer(in.Policy))
	out.Files = *(*map[string]string)(unsafe.Pointer(&in.Files))
	out.Entrypoint = in.Entrypoint
	return nil
}

// Convert_agent_PlaybookSpec_To_v1alpha1_PlaybookSpec is an autogenerated conversion function.
func Convert_agent_PlaybookSpec_To_v1alpha1_PlaybookSpec(in *agent.PlaybookSpec, out *PlaybookSpec, s conversion.Scope) error {
	return autoConvert_agent_PlaybookSpec_To_v1alpha1_PlaybookSpec(in, out, s)
}

func autoConvert_v1alpha1_PlaybookStatus_To_agent_PlaybookStatus(in *PlaybookStatus, out *agent.PlaybookStatus, s conversion.Scope) error {
	out.Phase = agent.PlaybookPhase(in.Phase)
	out.Conditions = *(*agent.Conditions)(unsafe.Pointer(&in.Conditions))
	out.Failed = in.Failed
	return nil
}

// Convert_v1alpha1_PlaybookStatus_To_agent_PlaybookStatus is an autogenerated conversion function.
func Convert_v1alpha1_PlaybookStatus_To_agent_PlaybookStatus(in *PlaybookStatus, out *agent.PlaybookStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_PlaybookStatus_To_agent_PlaybookStatus(in, out, s)
}

func autoConvert_agent_PlaybookStatus_To_v1alpha1_PlaybookStatus(in *agent.PlaybookStatus, out *PlaybookStatus, s conversion.Scope) error {
	out.Phase = PlaybookPhase(in.Phase)
	out.Conditions = *(*Conditions)(unsafe.Pointer(&in.Conditions))
	out.Failed = in.Failed
	return nil
}

// Convert_agent_PlaybookStatus_To_v1alpha1_PlaybookStatus is an autogenerated conversion function.
func Convert_agent_PlaybookStatus_To_v1alpha1_PlaybookStatus(in *agent.PlaybookStatus, out *PlaybookStatus, s conversion.Scope) error {
	return autoConvert_agent_PlaybookStatus_To_v1alpha1_PlaybookStatus(in, out, s)
}

func autoConvert_v1alpha1_PlaybookTemplateSpec_To_agent_PlaybookTemplateSpec(in *PlaybookTemplateSpec, out *agent.PlaybookTemplateSpec, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_PlaybookSpec_To_agent_PlaybookSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_PlaybookTemplateSpec_To_agent_PlaybookTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha1_PlaybookTemplateSpec_To_agent_PlaybookTemplateSpec(in *PlaybookTemplateSpec, out *agent.PlaybookTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PlaybookTemplateSpec_To_agent_PlaybookTemplateSpec(in, out, s)
}

func autoConvert_agent_PlaybookTemplateSpec_To_v1alpha1_PlaybookTemplateSpec(in *agent.PlaybookTemplateSpec, out *PlaybookTemplateSpec, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_agent_PlaybookSpec_To_v1alpha1_PlaybookSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_agent_PlaybookTemplateSpec_To_v1alpha1_PlaybookTemplateSpec is an autogenerated conversion function.
func Convert_agent_PlaybookTemplateSpec_To_v1alpha1_PlaybookTemplateSpec(in *agent.PlaybookTemplateSpec, out *PlaybookTemplateSpec, s conversion.Scope) error {
	return autoConvert_agent_PlaybookTemplateSpec_To_v1alpha1_PlaybookTemplateSpec(in, out, s)
}

func autoConvert_v1alpha1_Policy_To_agent_Policy(in *Policy, out *agent.Policy, s conversion.Scope) error {
	out.Timeout = (*metav1.Duration)(unsafe.Pointer(in.Timeout))
	out.BackoffLimit = (*int32)(unsafe.Pointer(in.BackoffLimit))
	return nil
}

// Convert_v1alpha1_Policy_To_agent_Policy is an autogenerated conversion function.
func Convert_v1alpha1_Policy_To_agent_Policy(in *Policy, out *agent.Policy, s conversion.Scope) error {
	return autoConvert_v1alpha1_Policy_To_agent_Policy(in, out, s)
}

func autoConvert_agent_Policy_To_v1alpha1_Policy(in *agent.Policy, out *Policy, s conversion.Scope) error {
	out.Timeout = (*metav1.Duration)(unsafe.Pointer(in.Timeout))
	out.BackoffLimit = (*int32)(unsafe.Pointer(in.BackoffLimit))
	return nil
}

// Convert_agent_Policy_To_v1alpha1_Policy is an autogenerated conversion function.
func Convert_agent_Policy_To_v1alpha1_Policy(in *agent.Policy, out *Policy, s conversion.Scope) error {
	return autoConvert_agent_Policy_To_v1alpha1_Policy(in, out, s)
}

func autoConvert_v1alpha1_SysInfo_To_agent_SysInfo(in *SysInfo, out *agent.SysInfo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_SysInfoSpec_To_agent_SysInfoSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_SysInfo_To_agent_SysInfo is an autogenerated conversion function.
func Convert_v1alpha1_SysInfo_To_agent_SysInfo(in *SysInfo, out *agent.SysInfo, s conversion.Scope) error {
	return autoConvert_v1alpha1_SysInfo_To_agent_SysInfo(in, out, s)
}

func autoConvert_agent_SysInfo_To_v1alpha1_SysInfo(in *agent.SysInfo, out *SysInfo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_agent_SysInfoSpec_To_v1alpha1_SysInfoSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_agent_SysInfo_To_v1alpha1_SysInfo is an autogenerated conversion function.
func Convert_agent_SysInfo_To_v1alpha1_SysInfo(in *agent.SysInfo, out *SysInfo, s conversion.Scope) error {
	return autoConvert_agent_SysInfo_To_v1alpha1_SysInfo(in, out, s)
}

func autoConvert_v1alpha1_SysInfoSpec_To_agent_SysInfoSpec(in *SysInfoSpec, out *agent.SysInfoSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_Network_To_agent_Network(&in.Network, &out.Network, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_SysInfoSpec_To_agent_SysInfoSpec is an autogenerated conversion function.
func Convert_v1alpha1_SysInfoSpec_To_agent_SysInfoSpec(in *SysInfoSpec, out *agent.SysInfoSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_SysInfoSpec_To_agent_SysInfoSpec(in, out, s)
}

func autoConvert_agent_SysInfoSpec_To_v1alpha1_SysInfoSpec(in *agent.SysInfoSpec, out *SysInfoSpec, s conversion.Scope) error {
	if err := Convert_agent_Network_To_v1alpha1_Network(&in.Network, &out.Network, s); err != nil {
		return err
	}
	return nil
}

// Convert_agent_SysInfoSpec_To_v1alpha1_SysInfoSpec is an autogenerated conversion function.
func Convert_agent_SysInfoSpec_To_v1alpha1_SysInfoSpec(in *agent.SysInfoSpec, out *SysInfoSpec, s conversion.Scope) error {
	return autoConvert_agent_SysInfoSpec_To_v1alpha1_SysInfoSpec(in, out, s)
}
