//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubeforce Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	config "k3f.io/kubeforce/agent/pkg/config"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AgentAuthentication)(nil), (*config.AgentAuthentication)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AgentAuthentication_To_config_AgentAuthentication(a.(*AgentAuthentication), b.(*config.AgentAuthentication), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.AgentAuthentication)(nil), (*AgentAuthentication)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_AgentAuthentication_To_v1alpha1_AgentAuthentication(a.(*config.AgentAuthentication), b.(*AgentAuthentication), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AgentX509Authentication)(nil), (*config.AgentX509Authentication)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AgentX509Authentication_To_config_AgentX509Authentication(a.(*AgentX509Authentication), b.(*config.AgentX509Authentication), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.AgentX509Authentication)(nil), (*AgentX509Authentication)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_AgentX509Authentication_To_v1alpha1_AgentX509Authentication(a.(*config.AgentX509Authentication), b.(*AgentX509Authentication), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Config)(nil), (*config.Config)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Config_To_config_Config(a.(*Config), b.(*config.Config), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Config)(nil), (*Config)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Config_To_v1alpha1_Config(a.(*config.Config), b.(*Config), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ConfigSpec)(nil), (*config.ConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigSpec_To_config_ConfigSpec(a.(*ConfigSpec), b.(*config.ConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ConfigSpec)(nil), (*ConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ConfigSpec_To_v1alpha1_ConfigSpec(a.(*config.ConfigSpec), b.(*ConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EtcdConfig)(nil), (*config.EtcdConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_EtcdConfig_To_config_EtcdConfig(a.(*EtcdConfig), b.(*config.EtcdConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.EtcdConfig)(nil), (*EtcdConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_EtcdConfig_To_v1alpha1_EtcdConfig(a.(*config.EtcdConfig), b.(*EtcdConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TLS)(nil), (*config.TLS)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TLS_To_config_TLS(a.(*TLS), b.(*config.TLS), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.TLS)(nil), (*TLS)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_TLS_To_v1alpha1_TLS(a.(*config.TLS), b.(*TLS), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_AgentAuthentication_To_config_AgentAuthentication(in *AgentAuthentication, out *config.AgentAuthentication, s conversion.Scope) error {
	if err := Convert_v1alpha1_AgentX509Authentication_To_config_AgentX509Authentication(&in.X509, &out.X509, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_AgentAuthentication_To_config_AgentAuthentication is an autogenerated conversion function.
func Convert_v1alpha1_AgentAuthentication_To_config_AgentAuthentication(in *AgentAuthentication, out *config.AgentAuthentication, s conversion.Scope) error {
	return autoConvert_v1alpha1_AgentAuthentication_To_config_AgentAuthentication(in, out, s)
}

func autoConvert_config_AgentAuthentication_To_v1alpha1_AgentAuthentication(in *config.AgentAuthentication, out *AgentAuthentication, s conversion.Scope) error {
	if err := Convert_config_AgentX509Authentication_To_v1alpha1_AgentX509Authentication(&in.X509, &out.X509, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_AgentAuthentication_To_v1alpha1_AgentAuthentication is an autogenerated conversion function.
func Convert_config_AgentAuthentication_To_v1alpha1_AgentAuthentication(in *config.AgentAuthentication, out *AgentAuthentication, s conversion.Scope) error {
	return autoConvert_config_AgentAuthentication_To_v1alpha1_AgentAuthentication(in, out, s)
}

func autoConvert_v1alpha1_AgentX509Authentication_To_config_AgentX509Authentication(in *AgentX509Authentication, out *config.AgentX509Authentication, s conversion.Scope) error {
	out.ClientCAFile = in.ClientCAFile
	out.ClientCAData = *(*[]byte)(unsafe.Pointer(&in.ClientCAData))
	return nil
}

// Convert_v1alpha1_AgentX509Authentication_To_config_AgentX509Authentication is an autogenerated conversion function.
func Convert_v1alpha1_AgentX509Authentication_To_config_AgentX509Authentication(in *AgentX509Authentication, out *config.AgentX509Authentication, s conversion.Scope) error {
	return autoConvert_v1alpha1_AgentX509Authentication_To_config_AgentX509Authentication(in, out, s)
}

func autoConvert_config_AgentX509Authentication_To_v1alpha1_AgentX509Authentication(in *config.AgentX509Authentication, out *AgentX509Authentication, s conversion.Scope) error {
	out.ClientCAFile = in.ClientCAFile
	out.ClientCAData = *(*[]byte)(unsafe.Pointer(&in.ClientCAData))
	return nil
}

// Convert_config_AgentX509Authentication_To_v1alpha1_AgentX509Authentication is an autogenerated conversion function.
func Convert_config_AgentX509Authentication_To_v1alpha1_AgentX509Authentication(in *config.AgentX509Authentication, out *AgentX509Authentication, s conversion.Scope) error {
	return autoConvert_config_AgentX509Authentication_To_v1alpha1_AgentX509Authentication(in, out, s)
}

func autoConvert_v1alpha1_Config_To_config_Config(in *Config, out *config.Config, s conversion.Scope) error {
	if err := Convert_v1alpha1_ConfigSpec_To_config_ConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Config_To_config_Config is an autogenerated conversion function.
func Convert_v1alpha1_Config_To_config_Config(in *Config, out *config.Config, s conversion.Scope) error {
	return autoConvert_v1alpha1_Config_To_config_Config(in, out, s)
}

func autoConvert_config_Config_To_v1alpha1_Config(in *config.Config, out *Config, s conversion.Scope) error {
	if err := Convert_config_ConfigSpec_To_v1alpha1_ConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_Config_To_v1alpha1_Config is an autogenerated conversion function.
func Convert_config_Config_To_v1alpha1_Config(in *config.Config, out *Config, s conversion.Scope) error {
	return autoConvert_config_Config_To_v1alpha1_Config(in, out, s)
}

func autoConvert_v1alpha1_ConfigSpec_To_config_ConfigSpec(in *ConfigSpec, out *config.ConfigSpec, s conversion.Scope) error {
	out.Port = in.Port
	if err := Convert_v1alpha1_TLS_To_config_TLS(&in.TLS, &out.TLS, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_AgentAuthentication_To_config_AgentAuthentication(&in.Authentication, &out.Authentication, s); err != nil {
		return err
	}
	out.ShutdownGracePeriod = in.ShutdownGracePeriod
	if err := Convert_v1alpha1_EtcdConfig_To_config_EtcdConfig(&in.Etcd, &out.Etcd, s); err != nil {
		return err
	}
	out.PlaybookPath = in.PlaybookPath
	return nil
}

// Convert_v1alpha1_ConfigSpec_To_config_ConfigSpec is an autogenerated conversion function.
func Convert_v1alpha1_ConfigSpec_To_config_ConfigSpec(in *ConfigSpec, out *config.ConfigSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigSpec_To_config_ConfigSpec(in, out, s)
}

func autoConvert_config_ConfigSpec_To_v1alpha1_ConfigSpec(in *config.ConfigSpec, out *ConfigSpec, s conversion.Scope) error {
	out.Port = in.Port
	if err := Convert_config_TLS_To_v1alpha1_TLS(&in.TLS, &out.TLS, s); err != nil {
		return err
	}
	if err := Convert_config_AgentAuthentication_To_v1alpha1_AgentAuthentication(&in.Authentication, &out.Authentication, s); err != nil {
		return err
	}
	out.ShutdownGracePeriod = in.ShutdownGracePeriod
	if err := Convert_config_EtcdConfig_To_v1alpha1_EtcdConfig(&in.Etcd, &out.Etcd, s); err != nil {
		return err
	}
	out.PlaybookPath = in.PlaybookPath
	return nil
}

// Convert_config_ConfigSpec_To_v1alpha1_ConfigSpec is an autogenerated conversion function.
func Convert_config_ConfigSpec_To_v1alpha1_ConfigSpec(in *config.ConfigSpec, out *ConfigSpec, s conversion.Scope) error {
	return autoConvert_config_ConfigSpec_To_v1alpha1_ConfigSpec(in, out, s)
}

func autoConvert_v1alpha1_EtcdConfig_To_config_EtcdConfig(in *EtcdConfig, out *config.EtcdConfig, s conversion.Scope) error {
	out.DataDir = in.DataDir
	out.CertsDir = in.CertsDir
	out.ListenPeerURLs = in.ListenPeerURLs
	out.ListenClientURLs = in.ListenClientURLs
	return nil
}

// Convert_v1alpha1_EtcdConfig_To_config_EtcdConfig is an autogenerated conversion function.
func Convert_v1alpha1_EtcdConfig_To_config_EtcdConfig(in *EtcdConfig, out *config.EtcdConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_EtcdConfig_To_config_EtcdConfig(in, out, s)
}

func autoConvert_config_EtcdConfig_To_v1alpha1_EtcdConfig(in *config.EtcdConfig, out *EtcdConfig, s conversion.Scope) error {
	out.DataDir = in.DataDir
	out.CertsDir = in.CertsDir
	out.ListenPeerURLs = in.ListenPeerURLs
	out.ListenClientURLs = in.ListenClientURLs
	return nil
}

// Convert_config_EtcdConfig_To_v1alpha1_EtcdConfig is an autogenerated conversion function.
func Convert_config_EtcdConfig_To_v1alpha1_EtcdConfig(in *config.EtcdConfig, out *EtcdConfig, s conversion.Scope) error {
	return autoConvert_config_EtcdConfig_To_v1alpha1_EtcdConfig(in, out, s)
}

func autoConvert_v1alpha1_TLS_To_config_TLS(in *TLS, out *config.TLS, s conversion.Scope) error {
	out.CertFile = in.CertFile
	out.PrivateKeyFile = in.PrivateKeyFile
	out.CertData = *(*[]byte)(unsafe.Pointer(&in.CertData))
	out.PrivateKeyData = *(*[]byte)(unsafe.Pointer(&in.PrivateKeyData))
	out.CipherSuites = *(*[]string)(unsafe.Pointer(&in.CipherSuites))
	out.TLSMinVersion = in.TLSMinVersion
	return nil
}

// Convert_v1alpha1_TLS_To_config_TLS is an autogenerated conversion function.
func Convert_v1alpha1_TLS_To_config_TLS(in *TLS, out *config.TLS, s conversion.Scope) error {
	return autoConvert_v1alpha1_TLS_To_config_TLS(in, out, s)
}

func autoConvert_config_TLS_To_v1alpha1_TLS(in *config.TLS, out *TLS, s conversion.Scope) error {
	out.CertFile = in.CertFile
	out.CertData = *(*[]byte)(unsafe.Pointer(&in.CertData))
	out.PrivateKeyFile = in.PrivateKeyFile
	out.PrivateKeyData = *(*[]byte)(unsafe.Pointer(&in.PrivateKeyData))
	out.CipherSuites = *(*[]string)(unsafe.Pointer(&in.CipherSuites))
	out.TLSMinVersion = in.TLSMinVersion
	return nil
}

// Convert_config_TLS_To_v1alpha1_TLS is an autogenerated conversion function.
func Convert_config_TLS_To_v1alpha1_TLS(in *config.TLS, out *TLS, s conversion.Scope) error {
	return autoConvert_config_TLS_To_v1alpha1_TLS(in, out, s)
}
