/*
Copyright 2022 The Kubeforce Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package templates

import (
	"fmt"
	"strings"

	"k8s.io/component-base/version"

	"k3f.io/kubeforce/cluster-api-provider-kubeforce/pkg/assets"
)

var (
	versionPrefix = sanitizeVersion(version.Get().GitVersion)
)

// GetName is the name of the playbook template generated by the controller..
func GetName(name assets.PlaybookName) string {
	return fmt.Sprintf("%s-%s", name, versionPrefix)
}

func sanitizeVersion(version string) string {
	i := strings.Index(version, "+")
	if i < 0 {
		return version
	}
	return version[:i]
}
