name: Build

on:
  pull_request:
    branches:
      - "main"
      - "release-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'

      - name: Run agent unit tests
        run: make agent-test

      - name: Run controller unit tests
        run: make controller-test

      - name: Build agent
        run: make agent

      - name: Build controller
        run: make controller-build
