name: release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v0.1.0, v1.0

permissions:
  contents: write # Allow to create a release.
  packages: write # Allow pushing Docker images

jobs:
  build:
    name: create draft release
    runs-on: ubuntu-latest
    steps:
      - name: login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'

      - name: Set env RELEASE_TAG
        run: echo "RELEASE_TAG=$(./hack/version.sh version)" >> $GITHUB_ENV

      - name: Build the controller docker images
        run: |
          make controller-build-all
      - name: Push the controller docker images
        run: |
          make controller-push-all
      - name: generate release artifacts
        run: |
          make release
      - name: generate release notes
        run: |
          make release-notes
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: _build/release/${{ env.RELEASE_TAG }}//*
          body_path: _build/releasenotes/${{ env.RELEASE_TAG }}/RELEASE_NOTES.md
