name: Verify

on:
  push:
    branches:
      - 'run-tests/**'
  pull_request:
    branches:
      - "main"
      - "release-*"

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: '^1.20'

      - name: Run all verify-* targets
        run: make verify
